name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.9.3
    - name: Compile
      run: mill project.compile
    # the server process is kept alive across steps,
    # so separate invocations of mill remain extremely fast!
    - name: Test
      run: mill helloindigo.test
